"""
This program was designed to run with python 3 in a Spyder environnement, with usual packages plus npTDMS,
cv2 and local libraries found in the folder diagnostics and utils of the environment. 
Only the imput parameter section should be modified.

They are: - [shot] int
              the number of the shot
          - [bias_type] str
              the way to bias the probes in the given shot
              Note that it can only be a temperature or ion_saturation_current bias
              Other bias type will trigger an error message
          - [data_type] str
              the type of data plotted
              Can be raw data or fluctuations (data minus mean value)
          - [path_to_data] str
              the name of the data folder with the full path to acceed it
          - [path_to_figure] str
              the name of the figure folder with the full path to acceed it
          - [fps] float
              the frame rate of the saved movie 
          - [length] int
              the time lenght in µs of the movie/image sequence
          - [sus_probes] numpy array
              the discarded probes considering their current or voltage plots
          - [k] int
              the extent of the colorbar in terms of standard variation of the signal

Take the data from the .txt files generated by extract_all_data.py (in the data folder).
Plot it into images and then a video. The obtained plots are stored in a sub folder the Figure folder created if not existing.
Can be raw or fluctuating data.
"""

#Find the path to local libraries (modify the PYTHON PATH)
import sys
sys.path.append('C:\\Users\\Saïd\\Downloads\\north_diagnostics\\diagnostics')
sys.path.append('C:\\Users\\Saïd\\Downloads\\north_diagnostics\\utils')
sys.path.append('C:\\Users\\Saïd\\Downloads\\north_diagnostics')

#Import all useful libraries
import numpy as np
import matplotlib.pyplot as plt
import os
import diagnostics.probe
import utils.dau

#Input parameters
shot = 10164
bias_type = 'ion_saturation_current' #Probes can be biased to measure 'current' or 'temperature' (the same bias is applied on every probe)
data_type = 'fluctuations' #We may be interested in the raw data or in their fluctuations. As a consequence, put 'raw' or 'fluctuations'.
path_to_data = 'E:/north_diagnostics/Data'
path_to_figure = 'E:/north_diagnostics/Figures'
fps = 15 #frame rate of the video
length = 200
sus_probes = []
k = 2




"""
Main program: from now, all shall remain untouched.
"""
#Extract and cleaning data from .txt file
data = np.genfromtxt(f"{path_to_data}/probe_data{shot}.txt", delimiter=';', skip_header=1)
bc = 2.26E-5 #in A
if data_type=='fluctuations':
  data[:,1:] = data[:,1:] - np.mean(data[:,1:], axis=0, keepdims=True)
  bc = 0
print(f"Data shot {shot} ({data_type}) loaded with success")

#Testing activated probes
activated_probes = []
for i in range(diagnostics.Probe.TOTAL_PROBES):
   if np.mean(data[:,i+1]) != 0 and i+1 not in sus_probes:
       activated_probes.append(True)
   else:
       activated_probes.append(False)

#Parameters for plotting a single colorbar
mean, std = np.mean(data[:length,1:]), np.std(data[:length,1:])
vmin, vmax = mean - k*std, mean + k*std
  
#Create a folder to store data if it doesn't exist
if not os.path.exists(f"{path_to_figure}/{shot}_{bias_type}_{data_type}/"):
    os.makedirs(f"{path_to_figure}/{shot}_{bias_type}_{data_type}/")
    print("A new directory for storing data was created")

#Create figure 
fig = plt.figure(figsize=(10,10))
  
#Plot all images of the vessel + the probes + the data for each time
for i in range(length): 
    output = utils.dau.plot_2D_data(data[i, :], shot, path_to_data, bias_type, data_type, i, activated_probes, vmin, vmax, fig, bc)
    plt.title(f"Shot {shot} {data_type} {bias_type} at time {data[i,0]:.6} s")
    plt.legend()
    plt.savefig(f"{path_to_figure}/{shot}_{bias_type}_{data_type}/{i}.jpg")
    plt.clf()
    
    print(output)
plt.close()

#Save those images in a movie (.avi or .tiff) => to be found in the figure folder
output = utils.dau.video_2D(data, shot, path_to_figure, bias_type, data_type, fps)
print(output)
