"""
Only the imput parameter section should be modified.

They are: - [shot] int
              the number of the shot
          - [path] str
              the name of the folder in which all the code architecture is
          - [current_value] float
              the value of the current in the vertical coils, only relevant when [data_origin] is simulation
          - [data_origin] str
              the way data were collected. Can be experiment or simulation.
          - [bias_type] str
              the way to bias the probes in the given shot
              Note that it can only be a temperature or ion_saturation_current bias
          - [k] int
              the extent of the colorbar in terms of standard variation of the signal

For experiment data, take the data from the .txt files generated by extract_all_data.py or the DDAQ file.
For simulation data, take the data from probeIsat_Bvertsweep.txt generated by COMSOL simulation.
Plot the normalized centered PDF for each probe, and the  maps of the four firsts statistical moments. 
The plots are stored in a sub folder the Figure folder created if not existing.
"""

#Find the path to local libraries (modify the PYTHON PATH)
import sys
sys.path.append('C:\\Users\\tulla\\Perso\\north_diagnostics\\diagnostics')
sys.path.append('C:\\Users\\tulla\\Perso\\north_diagnostics\\utils')
sys.path.append('C:\\Users\\tulla\\Perso\\north_diagnostics')

#Import all useful libraries
import numpy as np
import matplotlib.pyplot as plt
import os
import utils.dau



"""
Input parameters
"""
shot = 10168
path = 'C:/Users/tulla/Perso/north_diagnostics'
current_value = 10
data_origin = 'experiment'
bias_type = 'ion_saturation_current'
k = 3



"""
Main program: from now, all shall remain untouched.
"""

#Extract and cleaning data from .txt file
if data_origin == 'experiment':
      #Activated probes for that type of data
      studied_probes = np.array([1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,23,24,25,
                               26,27,28,29,30,31,32,33,38,39,40,41,42,43,44,45,46,47,48,49])
      all_data = utils.dau.read_probe_data(shot, path, 'ion_saturation_current', 1/75, studied_probes-1, 
                                         0, 1, False)
      data = all_data[150000:850000, :]
      print(f"Data shot {shot} loaded with success")
    
      #Create a folder to store data if it doesn't exist
      if not os.path.exists(f"{path}/Figures/{shot}_stat/"):
          os.makedirs(f"{path}/Figures/{shot}_stat/")
          print("A new directory for storing data was created")
        
elif data_origin == 'simulation': 
      #Activated probes for that type of data
      studied_probes = np.array([1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,
                                 26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50])
      
      all_data = np.genfromtxt(f"{path}/Data/probeIsat_Bvertsweep.txt", skip_header=5)
      print("Data probe loaded with success")
      
      #Take only the data for the given current value
      n_sweep = int(current_value//2.5)
      data = all_data[n_sweep*1001+100:(n_sweep+1)*1001-200, 1:]
      
      #Create a folder to store data if it doesn't exist
      if not os.path.exists(f"{path}/Figures/simu_stat_{int(current_value)}/"):
        os.makedirs(f"{path}/Figures/simu_stat_{int(current_value)}/")
        print("A new directory for storing data was created") 

#Send an error message if their is a mispelling in the data_origin variable
else:
    print('WARNING: the data origin is not recognized')
    sys.exit()
    
#Determination of the activated probes for the plot_2D_data function
activated_probes = []
for i in range(50):
    if i+1 in studied_probes:
        activated_probes.append(True)
    else:
        activated_probes.append(False)
        
#Calculate statistical moments of all probes and plot their distribution function
stat_data = np.zeros((4,51))
stat_data[:, 0] = np.ones(4)*500000E-6
fig = plt.figure(figsize=(10,10))
for i in range(50):
    if activated_probes[i]:
        #Taking the data of probe i
        curr_data = data[:, i+1]
        
        #Exclusion of extreme events (more than 5 times the standard deviation)
        mean_1 = np.mean(curr_data)
        sigma_1 = np.std(curr_data)
        data_clean = np.array([data[j, i+1] for j in range(len(curr_data)) 
                               if data[j, i+1]<mean_1+5*sigma_1 and data[j, i+1]>mean_1-5*sigma_1])
        
        #Computation of the moments
        m, sigma, skew, kurt = utils.dau.stat_analysis(data_clean, shot, current_value, path, 
                                                       data_origin, i+1, bias_type, fig, k)
        stat_data[0, i+1] = m 
        stat_data[1, i+1] = sigma
        stat_data[2, i+1] = skew
        stat_data[3, i+1] = kurt

#Plot the repartition map of the statistical data
name_stat = ['mean', 'standard_deviation', 'skewness', 'kurtosis']
bc = [np.mean(data[:,studied_probes]), 0, 0, 0]
for i in range(4):
    vmin, vmax = min(stat_data[i, studied_probes]), max(stat_data[i, studied_probes])
    output = utils.dau.plot_2D_data(stat_data[i, :], shot, path, bias_type, 'raw', i, activated_probes, 
                                    vmin, vmax, fig, bc[i])
    if data_origin == 'experiment':
        plt.title(f"Shot {shot} {name_stat[i]} of {bias_type}")
        plt.legend()
        plt.savefig(f"{path}/Figures/{shot}_stat/map_{name_stat[i]}.jpg")
            
    elif data_origin == 'simulation':
        plt.title(f"{name_stat[i]} of {bias_type} vertical current {current_value}")
        plt.legend()
        plt.savefig(f"{path}/Figures/simu_stat_{int(current_value)}/map_{name_stat[i]}.jpg")
        
    plt.clf()
    print(output)

#Plot the repartition of the skewness and the kurtosis with the name of each probe
for i in studied_probes:
    plt.text(stat_data[2, i], stat_data[3, i]-0.09, str(i), color='black', fontsize=8)
plt.scatter(stat_data[2, :], stat_data[3, :], color='blue', label='Data')

#Fit with a shaure function
model = np.polyfit(stat_data[2, :], stat_data[3, :], 2)
print(f"Fit parameters: {model}")
Sabs = np.linspace(-2, 2, 50)
SvsK_model = model[0]*Sabs**2+model[1]*Sabs+model[2] #model[1]*np.log(freq[30000:]) + model[0]
plt.plot(Sabs, SvsK_model, label=f'model: quadratic index {model[0]:.2f}')

#Legend and save
plt.xlabel('Skewness')
plt.ylabel('Kurtosis')
plt.title(f"Shot {shot} kurtosis as a function of skewness")
plt.legend()
plt.savefig(f"{path}/Figures/{shot}_stat/plot_skew_vs_kurt.jpg")
    
plt.close()
