"""
Only the imput parameter section should be modified.

They are: - [shot] int
              the number of the shot
          - [path] str
              the name of the folder in which all the code architecture is
          - [toroidal_current_value] float
              the value of the current in the toroidal coils, only relevant when [data_origin] is simulation
          - [vertical_current_value] float
              the value of the current in the vertical coils, only relevant when [data_origin] is simulation
          - [data_origin] str
              the way data were collected. Can be experiment or simulation.
          - [bias_type] str
              the way to bias the probes in the given shot
              Note that it can only be a temperature or ion_saturation_current bias
          - [k] int
              the extent of the colorbar in terms of standard variation of the signal

Take the data from the data from the DDAQ file or simulation file. The CRIO file is needed for the heating zone.
For simulation data, take the data from probeIsat_{}_{}.txt generated by COMSOL simulation.
Plot the normalized centered PDF for each probe, and the  maps of the four firsts statistical moments. 
The plots are stored in a sub folder the Figure folder created if not existing.
"""

#Find the path to local libraries (modify the PYTHON PATH)
import sys
sys.path.append('C:\\Users\\tulla\\Perso\\north_diagnostics\\diagnostics')
sys.path.append('C:\\Users\\tulla\\Perso\\north_diagnostics\\utils')
sys.path.append('C:\\Users\\tulla\\Perso\\north_diagnostics')

#Import all useful libraries
import numpy as np
import matplotlib.pyplot as plt
import os
import utils.dau



"""
Input parameters
"""
shot = 11233
path = 'C:/Users/tulla/Perso/north_diagnostics'
toroidal_current_value = 900
vertical_current_value = 0
data_origin = 'simulation'
bias_type = 'ion_saturation_current'
k = 3



"""
Main program: from now, all shall remain untouched.
"""

#Extract and cleaning data from .txt file
if data_origin == 'experiment':
      #Activated probes for that type of data
      studied_probes = np.array([1,2,3,5,6,7,8,9,10,11,13,14,15,17,18,20,21,23,24,25,
                               26,28,29,30,31,32,33,38,39,41,44,45,46,47,48,49])
      all_data = utils.dau.read_probe_data(shot, path, bias_type, 1/75, studied_probes-1, 0, 1, False)
      start = 600000
      end = 800000
      data = all_data[start:end, :]
      print(f"Data shot {shot} loaded with success")
    
      #Create a folder to store data if it doesn't exist
      if not os.path.exists(f"{path}/Figures/{shot}_stat/"):
          os.makedirs(f"{path}/Figures/{shot}_stat/")
          print("A new directory for storing data was created")
        
elif data_origin == 'simulation': 
      #Activated probes for that type of data
      studied_probes = np.array([1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,
                                 26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50])
      
      all_data = np.genfromtxt(f"{path}/Data/probeIsat_{int(vertical_current_value)}_{toroidal_current_value}.txt", skip_header=5)
      print("Data probe loaded with success")
      
      #Take only the data for the given current value
      start = 1500
      end = 5001
      data = - all_data[start:end, :]*1E3
      data[:, 0] = data[:, 0]*1E-3
      
      #all_data = np.genfromtxt(f"{path}/Data/probeIsat_fullmodel.txt", skip_header=5)
      #print("Data probe loaded with success")
      
      #Take only the data for the given current value
      #start = 1000
      #end = 5000
      #n_sweep = int((current_value)//20)
      #data = - all_data[n_sweep*5001+start:n_sweep*5001+end, :]*1E3
      #data[:, 0] = data[:, 0]*1E-3
      
      #Create a folder to store data if it doesn't exist
      if not os.path.exists(f"{path}/Figures/simu_stat_{int(vertical_current_value)}_{toroidal_current_value}/"):
        os.makedirs(f"{path}/Figures/simu_stat_{int(vertical_current_value)}_{toroidal_current_value}/")
        print("A new directory for storing data was created") 

#Send an error message if their is a mispelling in the data_origin variable
else:
    print('WARNING: the data origin is not recognized')
    sys.exit()
    
#Determination of the activated probes for the plot_2D_data function
activated_probes = []
for i in range(50):
    if i+1 in studied_probes:
        activated_probes.append(True)
    else:
        activated_probes.append(False)
        
#Calculate statistical moments of all probes and plot their distribution function
stat_data = np.zeros((4,51))
stat_data[:, 0] = np.ones(4)*(start+end)/2*1E-6
fig = plt.figure(figsize=(10,10))
for i in range(50):
    if activated_probes[i]:
        #Taking the data of probe i
        #curr_data = utils.dau.median_filter(data[:, i+1], 10) if too spiky data
        curr_data = data[:, i+1]
        
        #Exclusion of extreme events (more than 5 times the standard deviation)
        mean_1 = np.mean(curr_data)
        sigma_1 = np.std(curr_data)
        data_clean = np.array([data[j, i+1] for j in range(len(curr_data)) 
                               if data[j, i+1]<mean_1+5*sigma_1 and data[j, i+1]>mean_1-5*sigma_1])
        
        #Computation of the moments
        m, sigma, skew, kurt = utils.dau.stat_analysis(data_clean, shot, vertical_current_value,
                                                       toroidal_current_value, path, data_origin, 
                                                       i+1, bias_type, fig, k)
        stat_data[0, i+1] = m*1E3
        stat_data[1, i+1] = sigma*1E3
        stat_data[2, i+1] = skew
        stat_data[3, i+1] = kurt

#Plot the repartition map of the statistical data
name_stat = ['mean', 'standard_deviation', 'skewness', 'kurtosis']
bc = [2.26E-2, 0, 0, 0]
for i in range(4):
    vmin, vmax = min(stat_data[i, studied_probes]), max(stat_data[i, studied_probes])
    output = utils.dau.plot_2D_data(stat_data[i, :], shot, path, bias_type, 'raw', data_origin, toroidal_current_value, 
                                    i, activated_probes, vmin, vmax, fig, bc[i], layout=True)
    if data_origin == 'experiment':
        plt.title(f"Shot {shot} {name_stat[i]} of {bias_type}", fontsize=18)
        plt.legend(fontsize=18)
        plt.savefig(f"{path}/Figures/{shot}_stat/map_{name_stat[i]}_{start}to{end}.jpg")
            
    elif data_origin == 'simulation':
        plt.title(f"{name_stat[i]} of {bias_type} vertical current {vertical_current_value}", fontsize=18)
        plt.legend(fontsize=18)
        plt.savefig(f"{path}/Figures/simu_stat_{int(vertical_current_value)}_{toroidal_current_value}/map_{name_stat[i]}_{start}to{end}.jpg")
        
    plt.clf()
    print(output)

#Plot the repartition of the skewness and the kurtosis with the name of each probe
for i in studied_probes:
    plt.text(stat_data[2, i], stat_data[3, i]-0.09, str(i), color='black', fontsize=8)
plt.scatter(stat_data[2, :], stat_data[3, :], color='blue', label='Data')

#Fit with a sqaure function
model, covmodel = np.polyfit(stat_data[2, :], stat_data[3, :], 2, cov=True)
print(f"Fit parameters: {model} pm {2*np.sqrt(np.diag(covmodel))}")
Sabs = np.linspace(-2.5, 2.5, 50)
SvsK_model = model[0]*Sabs**2+model[1]*Sabs+model[2] #model[1]*np.log(freq[30000:]) + model[0]
plt.plot(Sabs, SvsK_model, label=f'model: quadratic index {model[0]:.2f} pm {2*np.sqrt(covmodel[0,0]):.2f}')

#Legend and save
plt.xlabel('Skewness', fontsize=18)
plt.ylabel('Kurtosis', fontsize=18)
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)
plt.title(f"Shot {shot} kurtosis as a function of skewness", fontsize=18)
plt.legend(fontsize=18)

if data_origin == 'experiment':
    plt.savefig(f"{path}/Figures/{shot}_stat/plot_skew_vs_kurt_{start}to{end}.jpg")
        
elif data_origin == 'simulation':
    plt.savefig(f"{path}/Figures/simu_stat_{int(vertical_current_value)}_{toroidal_current_value}/plot_skew_vs_kurt_{start}to{end}.jpg")

    
plt.close()
