"""
This program was designed to run with python 3 in a Spyder environnement, with usual packages plus npTDMS 
and local libraries found in the folder diagnostics and utils of the environment. 
Only the imput parameter section should be modified.

They are: - [shot] int
              the number of the shot
          - [path_to_data] str
              the name of the data folder with the full path to acceed it
          - [path_to_figure] str
              the name of the figure folder with the full path to acceed it
          - [current_value] float
              the value of the current in the vertical coils
          - [data_origin] str
              the way data were collected. Can be experiment or simulation.
          - [studied_probes] numpy array
              the number of the probes collecting data in the given shot
              Array with all probes: np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50])
          - [bias_type] str
              the way to bias the probes in the given shot
              Note that it can only be a temperature or ion_saturation_current bias
          - [k] int
              the extent of the colorbar in terms of standard variation of the signal

Take the data from the .txt files generated by extract_all_data.py (in the data folder).
Plot it into maps of kurtosis or skewness distribution. The plots are stored in a sub folder the Figure 
folder created if not existing.
"""

#Find the path to local libraries (modify the PYTHON PATH)
import sys
sys.path.append('C:\\Users\\Saïd\\Downloads\\north_diagnostics\\diagnostics')
sys.path.append('C:\\Users\\Saïd\\Downloads\\north_diagnostics\\utils')
sys.path.append('C:\\Users\\Saïd\\Downloads\\north_diagnostics')

#Import all useful libraries
import numpy as np
import matplotlib.pyplot as plt
import os
import utils.dau

#Input parameters
shot = 10165
path_to_data = 'E:/north_diagnostics/Data'
path_to_figure = 'E:/north_diagnostics/Figures'
current_value = 10
data_origin = 'simulation'
studied_probes = np.array([1,2,3,4,5,6,7,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50])
bias_type = 'ion_saturation_current'
k = 3



"""
Main program: from now, all shall remain untouched.
"""

#Extract and cleaning data from .txt file
if data_origin == 'experiment':
    all_data = utils.dau.read_probe_data(shot, path_to_data, 'ion_saturation_current', 1/75, studied_probes-1, 0, 1, path_to_figure, False)
    data = all_data[200000:800000, :]
    print(f"Data shot {shot} loaded with success")
    
    #Create a folder to store data if it doesn't exist
    if not os.path.exists(f"{path_to_figure}/{shot}_stat/"):
        os.makedirs(f"{path_to_figure}/{shot}_stat/")
        print("A new directory for storing data was created")
        
elif data_origin == 'simulation': 
      all_data = np.genfromtxt(f"{path_to_data}/probeIsat.txt", skip_header=5)
      print("Data probe loaded with success")
      
      #Take only the data for the given current value
      n_sweep = int(current_value//2.5)
      data = all_data[n_sweep*1001+100:(n_sweep+1)*1001-200, 1:]
      
      #Create a folder to store data if it doesn't exist
      if not os.path.exists(f"{path_to_figure}/simu_stat_{int(current_value)}/"):
        os.makedirs(f"{path_to_figure}/simu_stat_{int(current_value)}/")
        print("A new directory for storing data was created") 


#Determination of the activated probes for the plot_2D_data function
activated_probes = []
for i in range(50):
    if i+1 in studied_probes:
        activated_probes.append(True)
    else:
        activated_probes.append(False)
        
#Calculate statistical moments of all probes and plot their distribution function
stat_data = np.zeros((4,51))
fig = plt.figure(figsize=(10,10))
for i in range(50):
    if activated_probes[i]:
        m, sigma, skew, kurt = utils.dau.stat_analysis(data[:, i+1], shot, current_value, path_to_figure, data_origin, i+1, bias_type, fig, k)
        stat_data[0, i+1] = m 
        stat_data[1, i+1] = sigma
        stat_data[2, i+1] = skew
        stat_data[3, i+1] = kurt

#Plot the repartition map of the statistical data
name_stat = ['mean', 'standard_deviation', 'skewness', 'kurtosis']
bc = [np.mean(data[:,studied_probes]), 0, 0, 0]
for i in range(4):
    vmin, vmax = min(stat_data[i, :]), max(stat_data[i, :])
    output = utils.dau.plot_2D_data(stat_data[i, :], shot, path_to_data, bias_type, 'raw', i, activated_probes, vmin, vmax, fig, bc[i])
    if data_origin == 'experiment':
        plt.title(f"Shot {shot} {name_stat[i]} of {bias_type}")
        plt.legend()
        plt.savefig(f"{path_to_figure}/{shot}_stat/map_{name_stat[i]}.jpg")
            
    elif data_origin == 'simulation':
        plt.title(f"{name_stat[i]} of {bias_type} vertical current {current_value}")
        plt.legend()
        plt.savefig(f"{path_to_figure}/simu_stat_{int(current_value)}/map_{name_stat[i]}.jpg")
        
    plt.clf()
    print(output)
    
plt.close()
