"""
This program was designed to run with python 3 in a Spyder environnement, with usual packages plus local libraries
found in the folder diagnostics and utils of the environment. 
Only the imput parameter section should be modified.

They are: - [path] str
              the name of the folder in which all the code architecture is
          - [current_value] float
              the value of the current in the vertical coils, only relevant when [data_origin] is simulation

Take the data from the ne/pot_north.txt files generated by COMSOL simulation.
Computes the auto-correlation and cross-correlation of the quantities to measure a phase shift. 
The plots are stored in a sub folder the Figure folder created if not existing.
"""

#Find the path to local libraries (modify the PYTHON PATH)
import sys
sys.path.append('E:\\north_diagnostics\\diagnostics')
sys.path.append('E:\\north_diagnostics\\utils')
sys.path.append('E:\\north_diagnostics')

#Import all useful libraries
import numpy as np
import matplotlib.pyplot as plt
import os
import scipy.signal as scs
import utils.dau

#Input parameters
path = 'E:/north_diagnostics'
current_value = 0



"""
Main program: from now, all shall remain untouched.
"""
#Activated probes for that type of data
studied_probes = np.array([1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,
                         26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50])

#Extract and cleaning data from .txt file
ne_all_data = np.genfromtxt(f"{path}/Data/ne_north_fm.txt", skip_header=5)
pot_all_data = np.genfromtxt(f"{path}/Data/pot_north_fm.txt", skip_header=5)

length = 800-200
ne_data = ne_all_data[200:800, :]
pot_data = pot_all_data[200:800, :]
print("Data probe loaded with success")
      
#Create a folder to store data if it doesn't exist
if not os.path.exists(f"{path}/Figures/phase_{int(current_value)}/"):
    os.makedirs(f"{path}/Figures/phase_{int(current_value)}/")
    print("A new directory for storing data was created") 
        
#Calculate statistical moments of all probes and plot their distribution function
fig = plt.figure(figsize=(10,10))
for i in range(len(studied_probes)):
    print(f"Probe {studied_probes[i]}")
    probe = studied_probes[i]
    ne_data_renorm = (ne_data[:, probe]-np.mean(ne_data[:, probe]))/np.std(ne_data[:, probe])
    pot_data_renorm = (pot_data[:, probe]-np.mean(pot_data[:, probe]))/np.std(pot_data[:, probe])
    
    auto_corr_ne = scs.correlate(ne_data_renorm, ne_data_renorm, mode='same', method='auto')/length
    auto_corr_pot = scs.correlate(pot_data_renorm, pot_data_renorm, mode='same', method='auto')/length
    cross_corr = scs.correlate(pot_data_renorm, ne_data_renorm, mode='same', method='auto')/length
    
    #Period 
    freq, spectrum = utils.dau.frequency_fft(auto_corr_pot, 1E-5)
    f = freq[np.argmax(utils.dau.rolling_average(spectrum, 10))]
    print(f" Frequency: {f}Hz")
    
    #lag time 
    tau = (ne_data[np.argmax(cross_corr[int(299-1/(2E-5*f)):int(299+1+1/(2E-5*f))]), 0]-5)*1E-3
    print(f" Lag time: {tau}s")
    
    #Phase shift
    phase = 2*np.pi*f*tau*180/np.pi
    print(f" Phase shift: {phase}°")

    #Plot density and potential
    plt.subplot(2,2,1)
    plt.plot(ne_data[:, 0], ne_data[:, probe], color='r', linewidth=2.5, label='Electron density')
    plt.xlabel("$t$ [ms]", fontsize=10)
    plt.xticks(fontsize=8)
    plt.ylabel(r"$n_{e} [m^{-3}]$", fontsize=10)
    plt.yticks(fontsize=8)
    plt.legend()
    plt.twinx()
    plt.plot(pot_data[:, 0], pot_data[:, probe]+1, color='b', linewidth=2.5, label='Plasma potential')
    plt.ylabel(r"$V_{plasma}$ [V]", fontsize=10)
    plt.yticks(fontsize=8)
    plt.ylim(min(pot_data[:, probe]), max(pot_data[:, probe])+2)
    plt.legend()
    
    #Cross correlation of density and potential, potential in advance on density
    plt.subplot(2,2,2)
    plt.yticks(ticks=[], fontsize=8)
    plt.twinx()
    plt.plot(ne_data[:, 0]-5, cross_corr)
    plt.xlabel(r"$\tau$ [ms]", fontsize=10)
    plt.xticks(fontsize=8)
    plt.ylabel("Cross correlation of V and $n_{e}$", fontsize=10)
    plt.yticks(fontsize=8)
    plt.ylim((-1,1))
    
    #Autocorrelation of ne
    plt.subplot(2,2,3)
    plt.plot(ne_data[:, 0]-5, auto_corr_ne)
    plt.xlabel(r"$\tau$ [ms]", fontsize=10)
    plt.ylabel("Autocorrelation of $n_{e}$", fontsize=10)
    plt.xticks(fontsize=8)
    plt.yticks(fontsize=8)
    plt.ylim((-1,1))
    
    #Autocorrelation of V
    plt.subplot(2,2,4)
    plt.plot(ne_data[:, 0]-5, auto_corr_pot)
    plt.xlabel(r"$\tau$ [ms]", fontsize=10)
    plt.ylabel("Autocorrelation of V", fontsize=10)
    plt.xticks(fontsize=8)
    plt.yticks(fontsize=8)
    plt.ylim((-1,1))
    
    #Legend and save figure
    plt.suptitle(f"Simulation : Probe {probe}", fontsize=18)
    plt.savefig(f"{path}/Figures/phase_{int(current_value)}/probe{probe}", dpi=300)
    plt.clf()
    
plt.close()
