"""
This program was designed to run with python 3 in a Spyder environnement, with usual packages local 
libraries found in the folder utils of the environment. 
Only the imput parameter section should be modified.

They are: - [shot] int
              the number of the shot
          - [path_to_data] str
              the name of the data folder with the full path to acceed it
          - [path_to_figure] str
              the name of the figure folder with the full path to acceed it
          - [spectrum_type] str
              the type of Fourier transform applied to data. 
              Can be frequency or spatial.
          - [time_step] float
              the physical time step between two points in the data array
          - [current_value] float
              the value of the current in the vertical coils
          - [data_origin] str
              the way data were collected. 
              Can be experiment or simulation.
          - [studied_probes] numpy array
              the number of the probes collecting data in the given shot
              Array with all probes: np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50])
          - [av_size] int
              the length of the average segment
              Recommended values: 100 experiment and 20 simulation
          - [lb] int
              the low born for the domain of the model to fit spectral index
          - [hb] int
              the high born for the domain of the model to fit spectral index
              Recommended values lb, hb = 60, 310 (simulation) and lb, hb = 8000, 50000 (experiment)
              This may change from one spectrum to another

Take the data from the .txt files generated by extract_all_data.py (in the data folder).
Analyse spatial and temporal frequencies of the collected signals, only current measurement are fast enough
for that type of study though.
Possibility to plot a turbulent spectrum.
"""

#Find the path to local libraries
import sys
sys.path.append('C:\\Users\\Saïd\\Downloads\\north_diagnostics\\diagnostics')
sys.path.append('C:\\Users\\Saïd\\Downloads\\north_diagnostics\\utils')
sys.path.append('C:\\Users\\Saïd\\Downloads\\north_diagnostics')

#Import all useful libraries
import numpy as np
import matplotlib.pyplot as plt
import os
import utils.dau

#Input parameters
shot = 10164
path_to_data = 'E:/north_diagnostics/Data'
path_to_figure = 'E:/north_diagnostics/Figures'
spectrum_type = 'frequency' 
time_step = 1E-6
current_value = 0
data_origin = 'experiment'
studied_probes = np.array([1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,38,39,40,41,42,43,44,45,46,47,48,49])
av_size = 100
lb = 8000
hb = 40000






"""
Main program: from now, all shall remain untouched.
"""
# Array that will contains all the calculated spectral indices
spec_ind = []
  
#Extract and cleaning data from .txt file
if data_origin == 'experiment':
    data = utils.dau.read_probe_data(shot, path_to_data, 'ion_saturation_current', 1/75, studied_probes-1, 300E-3, 800E-3, path_to_figure, False)
    print(f"Data shot {shot} loaded with success")
    
    #Create a folder to store data if it doesn't exist
    if not os.path.exists(f"{path_to_figure}/{shot}_{spectrum_type}/"):
        os.makedirs(f"{path_to_figure}/{shot}_{spectrum_type}/")
        print("A new directory for storing data was created")
        
elif data_origin == 'simulation': 
      all_data = np.genfromtxt(f"{path_to_data}/probeIsat.txt", skip_header=5)
      print("Data probe loaded with success")
      
      #Take only the data for the given current value and keep only middle of the simulation to avoid 
      #side effects (end of power, homogeneous start)
      n_sweep = int(current_value//2.5)
      data = all_data[n_sweep*1001+100:(n_sweep+1)*1001-200, 1:]
      
      #Create a folder to store data if it doesn't exist
      if not os.path.exists(f"{path_to_figure}/simu_{spectrum_type}_{int(current_value)}/"):
        os.makedirs(f"{path_to_figure}/simu_{spectrum_type}_{int(current_value)}/")
        print("A new directory for storing data was created")  
    
else:
    print('WARNING: the data origin is not recognized')
    sys.exit()

#Plot the data of one probe and its Fourier transform
fig = plt.figure(figsize=(10,10))

for i in range(len(studied_probes)):
      print(studied_probes[i])
      
      #Calculation and smoothing of the Fourier transform
      curr_data = data[:, studied_probes[i]]
      freq, spectrum = utils.dau.frequency_fft(curr_data, studied_probes[i], time_step) 
      spectrum_filt = utils.dau.rolling_average(spectrum, av_size)
      
      #Plot the signal
      plt.subplot(1,2,1)
      plt.plot(data[:, 0]*1E3, data[:, studied_probes[i]]*1E3, label =f'Probe {studied_probes[i]}') 
      plt.xlabel("time (ms)")  
      plt.ylabel("Ion saturation current (mA)")

      #Plot the Fourier transform
      plt.subplot(1,2,2)
      plt.plot(freq, spectrum_filt, label =f'Temporal spectrum of probe {studied_probes[i]}') 
      model = np.polyfit(np.log(freq[lb:hb]),np.log(spectrum_filt[lb:hb]),1)
      spectrum_model = np.exp(model[1])*(freq[lb:hb])**model[0] #model[1]*np.log(freq[30000:]) + model[0]
      spec_ind.append(model[0])
      plt.plot(freq[lb:hb],spectrum_model,label=f'model: spectral index {model[0]:.2f}')
      
      #Add some legend
      plt.xlabel("Frequencies (Hz)")  
      plt.ylabel("Amplitude (UA)") 
      plt.xscale("log")
      plt.yscale("log")
      plt.suptitle(f"Signal and spectrum of probe {studied_probes[i]}")
      plt.legend()
      
      #Save the data
      if data_origin == 'experiment':
          plt.savefig(f"{path_to_figure}/{shot}_{spectrum_type}/probe{studied_probes[i]}.png")
      elif data_origin == 'simulation':
          plt.savefig(f"{path_to_figure}/simu_{spectrum_type}_{int(current_value)}/probe{studied_probes[i]}.png")
      
      #Prepare to plot a new figure
      plt.clf() 
      
plt.close()
print(spec_ind)
