"""
Only the imput parameter section should be modified.

They are: - [shot] int
              the number of the shot
          - [path] str
              the name of the folder in which all the code architecture is 
          - [spectrum_type] str
              the type of Fourier transform applied to data. 
              Can be frequency or spatial.
          - [toroidal_current_value] float
              the value of the current in the toroidal coils, only relevant when [data_origin] is simulation
          - [vertical_current_value] float
              the value of the current in the vertical coils, only relevant when [data_origin] is simulation
          - [data_origin] str
              the way data were collected. 
              Can be experiment or simulation.
          - [av_size] int
              the length of the average segment
              Recommended values: 100 experiment and 20 simulation
          - [lb] int
              the low born for the domain of the model to fit spectral index
          - [hb] int
              the high born for the domain of the model to fit spectral index
              Recommended values lb, hb = 60, 310 (simulation) and lb, hb = 8000, 50000 (experiment)
              This may change from one spectrum to another

Take the data from the .txt files generated by extract_all_data.py or the DDAQ file.
Analyse spatial and temporal frequencies of the collected signals, only experimental current measurement 
are fast enough and have enough points for that type of study though.
Not adapted to experimental data due to the phases transition.
"""

#Find the path to local libraries
import sys
sys.path.append('C:\\Users\\tulla\\Perso\\north_diagnostics\\diagnostics')
sys.path.append('C:\\Users\\tulla\\Perso\\north_diagnostics\\utils')
sys.path.append('C:\\Users\\tulla\\Perso\\north_diagnostics')

#Import all useful libraries
import numpy as np
import matplotlib.pyplot as plt
import os
import utils.dau

#Input parameters
shot = 11341
path = 'C:/Users/tulla/Perso/north_diagnostics'
spectrum_type = 'frequency' 
toroidal_current_value = 1000
vertical_current_value = 30
data_origin = 'simulation'
av_size = 20
lb = 7000
hb = 50000






"""
Main program: from now, all shall remain untouched.
"""
# Array that will contains all the calculated spectral indices
spec_ind = []

#Extract and cleaning data from .txt file
if spectrum_type == 'frequency':
    if data_origin == 'experiment':
          #Activated probes for that type of data
          studied_probes = np.array([1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,
                                   26,27,28,29,30,31,32,33,38,39,40,41,42,43,44,45,46,47,48,49])
          
          data = utils.dau.read_probe_data(shot, path, 'ion_saturation_current', 1/75, studied_probes-1, 
                                         300E-3, 800E-3, False)
          print(f"Data shot {shot} loaded with success")
        
          #Create a folder to store data if it doesn't exist
          if not os.path.exists(f"{path}/Figures/{shot}_{spectrum_type}/"):
              os.makedirs(f"{path}/Figures/{shot}_{spectrum_type}/")
              print("A new directory for storing data was created")
         
          #The time step between two recorded points
          time_step = 1E-6  
    
    elif data_origin == 'simulation': 
          #Activated probes for that type of data
          studied_probes = np.array([1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,
                                     26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50])
          
          all_data = np.genfromtxt(f"{path}/Data/probeIsat_{int(vertical_current_value)}_{toroidal_current_value}.txt", skip_header=5)
          print("Data probe loaded with success")
          
          #Take only the data for the given current value and keep only middle of the simulation to avoid 
          #side effects (end of power, homogeneous start)
          n_sweep = 0 #int(current_value//2.5)
          data = - all_data[n_sweep*5001+1500:n_sweep*5001+5001, :]*1E3
          data[:, 0] = data[:, 0]*1E-3
          
          #Create a folder to store data if it doesn't exist
          if not os.path.exists(f"{path}/Figures/simu_{spectrum_type}_{int(vertical_current_value)}_{toroidal_current_value}/"):
            os.makedirs(f"{path}/Figures/simu_{spectrum_type}_{int(vertical_current_value)}_{toroidal_current_value}/")
            print("A new directory for storing data was created")
            
          #The time step between two recorded points
          time_step = 1E-6
            
    #Send an error message if their is a mispelling in the data_origin variable
    else:
        print('WARNING: the data origin is not recognized')
        sys.exit()

    #Plot the data of one probe and its Fourier transform
    fig = plt.figure(figsize=(10,10))
    
    for i in range(len(studied_probes)):
          print(f"Probe {studied_probes[i]} processed")
          
          #Calculation and smoothing of the Fourier transform
          curr_data = data[:, studied_probes[i]]
          freq, spectrum = utils.dau.frequency_fft(curr_data, time_step) 
          spectrum_filt = utils.dau.rolling_average(spectrum, av_size)
          
          #Plot the signal
          #plt.subplot(1,2,1)
          #if data_origin == 'experiment':
          #    plt.plot(data[:, 0]*1E3, data[:, studied_probes[i]]*1E3, label =f'Probe {studied_probes[i]}')
          #else:
          #    plt.plot(data[:, 0], data[:, studied_probes[i]]*1E3, label =f'Probe {studied_probes[i]}')
          #plt.xlabel("time (ms)")  
          #plt.ylabel("Ion saturation current (mA)")
    
          #Plot the Fourier transform
          #plt.subplot(1,2,2)
          plt.plot(freq, spectrum, label =f'Temporal spectrum of probe {studied_probes[i]}') 
          plt.plot(freq, spectrum_filt, label =f'Temporal smoothed spectrum of probe {studied_probes[i]}') 
          #model = np.polyfit(np.log(freq[lb:hb]),np.log(spectrum_filt[lb:hb]),1)
          #spectrum_model = np.exp(model[1])*(freq[lb:hb])**model[0] #model[1]*np.log(freq[30000:]) + model[0]
          #spec_ind.append(model[0])
          #plt.plot(freq[lb:hb],spectrum_model,label=f'model: spectral index {model[0]:.2f}')
          
          #Add some legend
          plt.xlabel("Frequencies (Hz)", fontsize=18)  
          plt.ylabel("Amplitude (UA)", fontsize=18) 
          plt.xscale("log")
          plt.yscale("log")
          plt.title(f"Signal and spectrum of probe {studied_probes[i]}", fontsize=18)
          plt.legend(fontsize=18)
          plt.xticks(fontsize=18)
          plt.yticks(fontsize=18)
          
          #Save the data
          if data_origin == 'experiment':
              plt.savefig(f"{path}/Figures/{shot}_{spectrum_type}/probe{studied_probes[i]}.png")
          elif data_origin == 'simulation':
              plt.savefig(f"{path}/Figures/simu_{spectrum_type}_{int(vertical_current_value)}_{toroidal_current_value}/probe{studied_probes[i]}.png")
          
          #Prepare to plot a new figure
          plt.clf() 
          
    plt.close()
    print(spec_ind)

elif spectrum_type == 'spatial': #Not developped yet
    pass
    
    
    #Create figure 
    #fig = plt.figure(figsize=(10,10))
    
    #if data_origin == 'experiment':
    #      #Activated probes for that type of data
    #      studied_probes = np.array([1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,
    #                               26,27,28,29,30,31,32,33,38,39,40,41,42,43,44,45,46,47,48,49])
    #      
    #      #collect pictures data non on doit générer une image sans les légendes...
    #      all_data = utils.dau.read_probe_data(shot, path, 'ion_saturation_current', 1/75, 
    #                                         studied_probes-1, 500000E-6, 501000E-6, False)
    #      data = all_data
    #      data[:,1:] = data[:,1:] - np.mean(data[:,1:], axis=0, keepdims=True)
    #      print(f"Data shot {shot} loaded with success")
    #    
    #      #Create a folder to store data if it doesn't exist
    #      if not os.path.exists(f"{path}/Figures/{shot}_{spectrum_type}/"):
    #          os.makedirs(f"{path}/Figures/{shot}_{spectrum_type}/")
    #          print("A new directory for storing data was created")
    #          
    #      #Determination of the activated probes for the plot_2D_data function
    #      activated_probes = []
    #      for i in range(50):
    #          if i+1 in studied_probes:
    #              activated_probes.append(True)
    #          else:
    #              activated_probes.append(False)
    #              
    #      #Data treatment
    #      for i in range(len(data[:, 0])):
    #          #Generate the images
    #          output = utils.dau.plot_2D_data(data[i, :], shot, path, 'ion_saturation_current', 'fluctuations', i, 
    #                                     activated_probes, min(data[i, :]), max(data[i, :]), fig, 0, layout=False)
    #          plt.axis('off')
    #          plt.savefig(f"{path}/Figures/fig.png")
    #          plt.clf()
    #          
    #          #Read the image and convert it into a gray scale numpy array
    #          image_data = plt.imread(f"{path}/Figures/fig.png")
    #          m, n, p = np.shape(image_data)
    #          image_gray = np.zeros((m, n))
    #          image_gray = 0.2126*image_data[:, :, 0]+0.7152*image_data[:, :, 1]+0.0722*image_data[:, :, 2]
    #          space_scale = 0.25/372 #m/pixel (measured on imageJ)
    #          
    #          #Switch to polar coordinates
    #          rows, cols = image_gray.shape
    #          crow, ccol = rows // 2, cols // 2
    #          x, y = np.meshgrid(np.linspace(-crow, crow, rows)*space_scale, np.linspace(-ccol, ccol, cols)*space_scale)
    #
    #          #Polar coordinates of the spectrum
    #          r = np.sqrt(x**2 + y**2)
    #          theta = np.arctan2(y, x)
    #          
    #          #Polar representation of the map
    #          # 4. Définir la nouvelle grille polaire (rayon, angle)
    #          # On définit le rayon max et le nombre de points
    #          max_r = min(crow, ccol)
    #          r_new = np.linspace(0, max_r, max_r)
    #          theta_new = np.linspace(-np.pi, np.pi, 360) # 360 degrés
    #          R_new, Theta_new = np.meshgrid(r_new, theta_new)
    #
    #          # 5. Interpolation : Convertir du Cartésien au Polaire
    #          # On convertit R_new, Theta_new en X, Y pour interpoler
    #          X_new = R_new * np.cos(Theta_new) + ccol
    #          Y_new = R_new * np.sin(Theta_new) + crow
    #
    #          # Interpolation (cette étape peut être lente pour de grandes images)
    #           polar_fft = griddata((x.flatten() + ccol, y.flatten() + crow), magnitude_spectrum.flatten()(X_new, Y_new), method='linear')
    #
    #          #Compute the 2D spatial Fourier transform
    #          space_step = 1
    #          kx, ky, spectrum = utils.dau.spatial_fft(data, space_step)
    #          
    #          print(output)
    #          
    #      #Delete the blank figure at the end of the treatment
    #      os.remove(f"{path}/Figures/fig.png")
    #      
    #elif data_origin == 'simulation': 
    #      #Activated probes for that type of data
    #      studied_probes = np.array([1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,
    #                                 26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50])
    #      
    #      #collect pictures data => better to do it in time with the images directly generated by COMSOL with
    #      #better spatial resolution
    #     image_folder = f"{path}/Figures/{int(current_value)}_ion_saturation_current_fluctuations/"
    #      images = [img for img in os.listdir(image_folder) if img.endswith((".jpg", ".jpeg", ".png"))]
    #      images.sort()
    #      print("Data probe loaded with success")
    #      
    #      
    #      #Create a folder to store data if it doesn't exist
    #      if not os.path.exists(f"{path}/Figure/simu_{spectrum_type}_{int(current_value)}/"):
    #        os.makedirs(f"{path}/Figure/simu_{spectrum_type}_{int(current_value)}/")
    #        print("A new directory for storing data was created")
    #        
    #
    #        
    #Send an error message if their is a mispelling in the data_origin variable
    #else:
    #    print('WARNING: the data origin is not recognized')
    #    sys.exit()
   
else:
    print('WARNING: the spectrum type is not recognized')
    sys.exit()
